name: CI Pipeline for GOlang Project

on:
    push:
        branches:
            - main
        paths_ignore:
            - .gitignore
            - README.md

jobs:
    build-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.5'  # Specify the Go version you want to use
            - run: |
                 go version
                 echo "Go version set up successfully."

            - name: Install Dependencies
              run: |
                go mod download
                echo "Dependencies installed successfully."

            - name: Build the Project
              run: |
                go build -o go-web-app .
                echo "Project built successfully."

            - name: Run Unit Tests
              run: go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Run go-lint
              uses: golangci/golangci-lint-action@v8
              with:
                version: v2.1  # Specify the version of golangci-lint you want to use
            