name: CI Pipeline for GOlang Project

on:
    push:
        branches:
            - main
        paths-ignore:
            - .gitignore
            - README.md
            - helm/go-web-app-chart/values.yaml

jobs:
    build-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.5'  # Specify the Go version you want to use
            - run: |
                 go version
                 echo "Go version set up successfully."

            - name: Install Dependencies
              run: |
                go mod download
                echo "Dependencies installed successfully."

            - name: Build the Project
              run: |
                go build -o go-web-app .
                echo "Project built successfully."

            - name: Run Unit Tests
              run: go test ./...

    code-quality:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Run go-lint
              uses: golangci/golangci-lint-action@v8
              with:
                version: v2.1  # Specify the version of golangci-lint you want to use

    docker-build-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                file: Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id}}

    docker-image-scan:
        runs-on: ubuntu-latest
        needs: docker-build-push

        steps:
          - name: Run Trivy vulnerability scanner
            uses: aquasecurity/trivy-action@0.28.0
            with:
              image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.run_id }}'
              format: 'table'
              exit-code: '1'
              ignore-unfixed: true
              vuln-type: 'os,library'
              severity: 'CRITICAL,HIGH'

    Update-k8s-manifest:
        runs-on: ubuntu-latest
        needs: docker-build-push

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.TOKEN }}

            - name: Update Kubernetes Manifest
              run: |
                sed -i "s|tag: .*|tag: ${{ github.run_id }}|g" helm/go-web-app-chart/values.yaml
                git config --global user.name "Ramesh"
                git config --global user.email "rameshpatil@gmail.com"
                git add helm/go-web-app-chart/values.yaml
                git commit -m "Chore:[Update image tag to ${{ github.run_id }}"]
                git push origin main
